/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElCard: typeof import('element-plus/es')['ElCard'];
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElLink: typeof import('element-plus/es')['ElLink'];
        ElRadio: typeof import('element-plus/es')['ElRadio'];
        ElText: typeof import('element-plus/es')['ElText'];
        IEpLock: typeof import('~icons/ep/lock')['default'];
        IEpUser: typeof import('~icons/ep/user')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
