/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElAside: typeof import('element-plus/es')['ElAside'];
        ElAvatar: typeof import('element-plus/es')['ElAvatar'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup'];
        ElCard: typeof import('element-plus/es')['ElCard'];
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
        ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
        ElCol: typeof import('element-plus/es')['ElCol'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
        ElDialog: typeof import('element-plus/es')['ElDialog'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElFooter: typeof import('element-plus/es')['ElFooter'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElImage: typeof import('element-plus/es')['ElImage'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElLink: typeof import('element-plus/es')['ElLink'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElRadio: typeof import('element-plus/es')['ElRadio'];
        ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
        ElSwitch: typeof import('element-plus/es')['ElSwitch'];
        ElTable: typeof import('element-plus/es')['ElTable'];
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
        ElTag: typeof import('element-plus/es')['ElTag'];
        ElTimeline: typeof import('element-plus/es')['ElTimeline'];
        ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem'];
        ElTimePicker: typeof import('element-plus/es')['ElTimePicker'];
        ElUpload: typeof import('element-plus/es')['ElUpload'];
        IEpDocument: typeof import('~icons/ep/document')['default'];
        IEpEdit: typeof import('~icons/ep/edit')['default'];
        IEpExpand: typeof import('~icons/ep/expand')['default'];
        IEpFinished: typeof import('~icons/ep/finished')['default'];
        IEpHomeFilled: typeof import('~icons/ep/home-filled')['default'];
        IEpList: typeof import('~icons/ep/list')['default'];
        IEpLock: typeof import('~icons/ep/lock')['default'];
        IEpNotebook: typeof import('~icons/ep/notebook')['default'];
        IEpNoteBook: typeof import('~icons/ep/note-book')['default'];
        IEpSearch: typeof import('~icons/ep/search')['default'];
        IEpTickets: typeof import('~icons/ep/tickets')['default'];
        IEpUploadFilled: typeof import('~icons/ep/upload-filled')['default'];
        IEpUser: typeof import('~icons/ep/user')['default'];
        IEpUsers: typeof import('~icons/ep/users')['default'];
        LeftNav: typeof import('./src/components/leftNav.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        TopNav: typeof import('./src/components/topNav.vue')['default'];
    }
}
