/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup'];
        ElCard: typeof import('element-plus/es')['ElCard'];
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElImage: typeof import('element-plus/es')['ElImage'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElLink: typeof import('element-plus/es')['ElLink'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElPopover: typeof import('element-plus/es')['ElPopover'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        ElSwitch: typeof import('element-plus/es')['ElSwitch'];
        ElTable: typeof import('element-plus/es')['ElTable'];
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
        ElTimeline: typeof import('element-plus/es')['ElTimeline'];
        ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem'];
        IEpLock: typeof import('~icons/ep/lock')['default'];
        IEpMinus: typeof import('~icons/ep/minus')['default'];
        IEpPlus: typeof import('~icons/ep/plus')['default'];
        IEpUser: typeof import('~icons/ep/user')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        TopNav: typeof import('./src/components/topNav.vue')['default'];
    }
}
